services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # Add other environment variables as needed, for example:
      # - API_KEY=${API_KEY}
    volumes:
      - ./:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload
    # If you need to wait for other services (like a database), you can use depends_on:
    # depends_on:
    #   - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # qdrant:
  #   image: qdrant/qdrant:v1.3.0
  #   restart: on-failure
  #   ports:
  #     - "6335:6335"
